maksuturva/woocommerce_payment_module

- includes/class-wc-gateway-implementation-maksuturva.php
Create fee payment rows and calculate totals so that they match the
rows.
Fixes #4
> Support fees

- includes/class-wc-gateway-admin-form-fields.php
- includes/class-wc-gateway-implementation-maksuturva.php
- includes/class-wc-gateway-maksuturva.php
- includes/class-wc-payment-checker-maksuturva.php
- includes/class-wc-utils-maksuturva.php
- readme.md
- templates/frontend/payment-method-estonia-payments-form.php
- wc-maksuturva.php
Allow checkout without some address information
> Estonian special delivery functionality

- includes/class-wc-gateway-implementation-maksuturva.php
- readme.md
- wc-maksuturva.php
* Fixed selected payment method undefined index -error after payment is successful
* Fixed deprecated item product data access
> Maintenance release

- docs/TESTING INSTRUCTIONS.md
- includes/class-wc-gateway-maksuturva.php
- languages/wc-maksuturva-fi_FI.po
- readme.md
- wc-maksuturva.php
* Fixed the checkout page was broken if the module was unable to communicate the backend API
* Changed the admin page fields order
> Svea fix 202106

- includes/class-wc-gateway-abstract-maksuturva.php
- includes/class-wc-meta-box-maksuturva.php
- includes/class-wc-payment-checker-maksuturva.php
- readme.md
- wc-maksuturva.php
> Sq 202203001

- includes/class-wc-payment-checker-maksuturva.php
> Sq 202203002

- includes/class-wc-gateway-admin-form-fields.php
- readme.md
- wc-maksuturva.php
* Fixed admin panel crash when there were no additional tax rates
> Tax 20220310

- readme.md
- templates/frontend/payment-method-estonia-payments-form.php
- templates/frontend/payment-method-form.php
- wc-maksuturva.php
* Fixed the handling fee display in the checkout payment selection page
> Hf 20220313

- includes/class-wc-svea-delivery-handler.php
- readme.md
- wc-maksuturva.php
* Changed Delivery info code from UNRDL -> ODLVR
> Delivery 20220405

- readme.md
- wc-maksuturva.php
* Fixed the part payment widget to work with included or excluded tax catalog prices
> Part Payment Widget fix

- includes/class-wc-gateway-implementation-maksuturva.php
- readme.md
- wc-maksuturva.php
* Added hook support for external payment ids
> Pmtid20221213

- includes/class-wc-gateway-maksuturva.php
- includes/class-wc-payment-maksuturva.php
- includes/class-wc-payment-method-select.php
> SD2Q-10 display payment method on order page

- includes/class-wc-gateway-maksuturva.php
- includes/class-wc-meta-box-maksuturva.php
- includes/class-wc-payment-maksuturva.php
- readme.md
- wc-maksuturva.php
Fixed errors on the admin order page when the payment method is not Svea
> Zo20230218

- CHANGELOG.md
- RELEASE.md
- includes/class-wc-gateway-implementation-maksuturva.php
* Fixed support for extra fees
* WC 7.5.0 tested
> Surcharge20230318

- .gitignore
- CHANGELOG.md
- README.md
- RELEASE.md
- includes/class-wc-gateway-abstract-maksuturva.php
- templates/frontend/payment-method-form-additional.php
- wc-maksuturva.php
* Changed default payment method order when initializing the module first time
* Changed pmt_row_desc to be "-" always
> Default payment method order change

- CHANGELOG.md
- README.md
- includes/class-wc-gateway-maksuturva.php
- wc-maksuturva.php
* Changed to show the user error text when payment returns error
> Gi 20231008

- .github/workflows/svea-release.yml
- CHANGELOG.md
- README.md
- RELEASE.md
- wc-maksuturva.php
Added feature flag to describe incompatiblity with new WooCommerce blocks mode
> Blocks feature flag

- .github/workflows/svea-release.yml
- CHANGELOG.md
- README.md
- RELEASE.md
- includes/class-wc-gateway-admin-form-fields.php
- wc-maksuturva.php
* Added "After add to cart form" location option for the Part Payment Widget
> Added new location for Part Payment Widget

- CHANGELOG.md
- README.md
- RELEASE.md
- includes/class-wc-gateway-maksuturva.php
- includes/class-wc-meta-box-maksuturva.php
- wc-maksuturva.php
* Fixed the meta box on the admin page when creating a new order and HPOS mode enabled
> Adminfix 20240125

- CHANGELOG.md
- includes/class-wc-gateway-admin-form-fields.php
- includes/class-wc-svea-api-request-handler.php
- wc-maksuturva.php
Display part payment widget according to the settings in WooCommerce admin and the settings defined in Svea API.
> Part payment widget visibility adjustments

- includes/class-wc-payment-method-select.php
Reverts maksuturva/woocommerce_payment_module#72
> Revert "Use more safe alternative for fetching plugin dir"

- CHANGELOG.md
- includes/class-wc-gateway-abstract-maksuturva.php
> Fetch response body before parsing

- CHANGELOG.md
- README.md
- RELEASE.md
- includes/class-wc-payment-checker-maksuturva.php
- includes/class-wc-svea-refund-handler.php
- wc-maksuturva.php
* Fixed a strtime warning in the status query
* Fixed logic for checking amount if the refund is full or partial refund
> Fixed refund logic

- .github/workflows/svea-release.yml
- CHANGELOG.md
- README.md
- RELEASE.md
- includes/class-wc-svea-part-payment-calculator.php
- scripts/part-payment-calculator-variable-product.js
- wc-maksuturva.php
* 285035: Add variable product support for part payment widget
> Part payment variable config

- CHANGELOG.md
- README.md
- includes/class-wc-gateway-maksuturva.php
Allow the redirect url to be filtered
> Redirect failed payment requests to checkout
